config/routes.rb
Hopscotch::Application.routes.draw do
  
  resources :locations
  resources :registrations
  resources :users

  root to: 'main#bac', as: 'bac'

  get "login" => "auth#login", :as => :login
  get "logout" => "auth#logout", :as => :logout
  post "do_login" => "auth#do_login", :as => :do_login
  

  get "bac" => "main#get_bac", :as => :get_bac
  post "bac" => "main#set_bac", :as => :set_bac
  get "admin" => "main#admin", :as => :admin

  get "options" => "main#choose", :as => :choose
  get "options/bars" => "main#bars", :as => :bars
  get "options/food" => "main#food", :as => :food
  get "options/uber" => "main#uber", :as => :uber
  get "options/twilio" => "main#twilio", :as => :twilio

  get "hops" => "hops#index", :as => :hops
  get "hops/new" => "hops#new", :as => :new_hop 
  get "hops/current" => "hops#current", :as => :current_hop
  get "hops/leave" => "hops#leave", :as => :leave_hop
  get "hops/end" => "hops#end_hop", :as => :end_hop
  get "hops/uber_end" => "hops#uber_end", :as => :uber_end
  post "hops/create" => "hops#create", :as => :create_hop
  get "hops/locations" => "hops#pick_locations", :as => :pick_locations
  post "hops/set" => "hops#set_locations", :as => :set_locations
  get "hops/planned" => "hops#plan_created", :as => :plan_created
  get "hops/destination" => "hops#destination", :as => :destination
  post "hops/save_destination" => "hops#save_destination", :as => :save_destination

end

app/controllers/main_controller.rb
require 'net/http'
require 'time'

class MainController < ApplicationController

	before_filter :get_logged_in_user

	def bac
		user = User.find(session[:user_id])
		if user.current_hop.nil?
			redirect_to new_hop_url
		end
		@booze_level = user.booze_level
	end

	def get_bac
		user = User.find(session[:user_id])
		# hard-coded latitude and longitude for now
		response = Net::HTTP.get_response(URI("http://mobile.bactrack.com/v1/readings/?lat_center=42.358675&lng_center=-71.096509&radius_meters=1000&format=json")).body
		# a few times it returned a 400 Bad Request message instead of content, so this checks for that
		unless response.include? "Bad Request"
			bacobjects = JSON.parse(response)["objects"]
			mostrecentbac = nil
			mostrecenttimestamp = "1970-01-01T00:00:00" # start of epoch
			unless bacobjects.nil?
				bacobjects.each do |b|
					# 10261 should become the actual user's BACtrack id
					if b["person"] == "/internal_v1/users/" + user.bactrack_id + "/" && b["timestamp"] > mostrecenttimestamp
						mostrecentbac = b["bac_level"]
						mostrecenttimestamp = b["timestamp"]
					end
				end
			end
		end

		user = User.find(session[:user_id])
		user.latest_bac = mostrecentbac
		# BACtrack knows we're in EST but it thinks EST is 4 hours ahead of where it actually is
		mostrecenttimestamp = Time.parse(mostrecenttimestamp).advance(:hours => -4).strftime("%l:%M%p %B %e, %Y")
		session[:timestamp] = mostrecenttimestamp

		# Find what their drunk emoji should be 
		user.drunk_emoji = get_drunk_emoji(mostrecentbac)

		# Find what their user interface should look like
		user.booze_level = get_booze_level(mostrecentbac)

		user.save
		redirect_to choose_url
	end

	def admin
	end

	def set_bac
		@mostrecentbac = params[:bac].to_f
		@user = User.find(session[:user_id])
		@user.latest_bac = @mostrecentbac
		session[:timestamp] = nil

		# Find what their drunk emoji should be 
		@user.drunk_emoji = get_drunk_emoji(@mostrecentbac)

		# Find what their user interface should look like
		@user.booze_level = get_booze_level(@mostrecentbac)

		@user.save
		redirect_to choose_url
	end

	def choose
		@user = User.find(session[:user_id])
		@time = session[:timestamp]
		bars()
		uber()
	end

	def bars
		user = User.find(session[:user_id])
		firstname = user.first
		lastname = user.last
		phone = user.phone

		#uberdestination = "229%20Commonwealth%20Ave%2C%20Boston%2C%20MA%2002116"
		@uberurl_1 = "https://m.uber.com/sign-up?client_id=a-RTv0w8VfNjNR0oTUio1LXBDrjrBIUx"
		@uberurl_1 += "&first_name="+firstname+"&last_name="+lastname+"&mobile_phone="+phone #+"&dropoff_address="+uberdestination
		@uberurl_2 = "&dropoff_latitude="
		@uberurl_3 = "&dropoff_longitude="

		# TODO: get actual lat and long from user
		lat = "42.360986"
		long = "-71.096849"
		max_width = "100" #measured in px
		bars_request_string = "https://maps.googleapis.com/maps/api/place/nearbysearch/json?key=AIzaSyBaaEBm7WetJlxmSCcShqvWSqttq63LTB8&location="+lat+","+long+"&rankby=distance&types=bar|night_club"
		bars_uri = URI.parse(URI.encode(bars_request_string))
		bars_https = Net::HTTP.new(bars_uri.host, bars_uri.port)
		bars_https.use_ssl = true
		bars_https.verify_mode = OpenSSL::SSL::VERIFY_NONE # this is NOT secure but Google's API is a free service and we aren't sharing real user data
		bars_request = Net::HTTP::Get.new(bars_uri.request_uri)
		bars_response = bars_https.request(bars_request).body
		results = JSON.parse(bars_response)["results"]
		@barlist = Array.new
		results.each do |r|
			barname = r["name"]
			baraddress = r["vicinity"]
			barlat = r["geometry"]["location"]["lat"]
			barlong = r["geometry"]["location"]["lng"]
			barrating = r["rating"]
			baricon = r["icon"]
			if baricon.include? "wine"
				bartype = "wine"
			else
				bartype = "bar"
			end
			@barlist << {:name => barname, :address => baraddress, :lat => barlat, :long => barlong, :rating => barrating, :type => bartype}
		end
	end

	def food
	end

	def uber
		user = User.find(session[:user_id])
		reg = Registration.find(user.current_hop)
		firstname = user.first
		lastname = user.last
		phone = user.phone

		#uberdestination = "229%20Commonwealth%20Ave%2C%20Boston%2C%20MA%2002116"
		@uberurl = "https://m.uber.com/sign-up?client_id=a-RTv0w8VfNjNR0oTUio1LXBDrjrBIUx"
		@uberurl += "&first_name="+firstname+"&last_name="+lastname+"&mobile_phone="+phone #+"&dropoff_address="+uberdestination
		@uberurl += "&dropoff_latitude=" + reg.final_destination_lat
		@uberurl += "&dropoff_longitude=" + reg.final_destination_long
	end

	def twilio
		# TODO: read this value from database
		phone = "+13174167556"
		account_sid = "AC698f80b23e2836098d6f58cf7498e4e0"
		auth_token = "01d2cb9b9bea47ef35df3b1d08c17eb7"
		@client = Twilio::REST::Client.new account_sid, auth_token
		message = @client.account.messages.create(
			:body => "This is a reminder text from Hopscotch",
			:to => phone,
			:from => "+13172520150")
		puts message.sid
	end

	def get_booze_level(bac)
		if bac == 0
			return 0
		elsif bac < 0.07
			return 1
		elsif bac < 0.13
			return 2
		else 
			return 3
		end
	end

	def get_drunk_emoji(bac)
		if bac == 0
			return "https://abs.twimg.com/emoji/v1/72x72/1f610.png"
		elsif bac < 0.02
			return "https://abs.twimg.com/emoji/v1/72x72/1f62f.png"
		elsif bac < 0.03
			return "https://abs.twimg.com/emoji/v1/72x72/263a.png"
		elsif bac < 0.04
			return "https://abs.twimg.com/emoji/v1/72x72/1f61a.png"
		elsif bac < 0.05
			return "https://abs.twimg.com/emoji/v1/72x72/1f601.png"
		elsif bac < 0.07
			return "https://abs.twimg.com/emoji/v1/72x72/1f61b.png"
		elsif bac < 0.09
			return "https://abs.twimg.com/emoji/v1/72x72/1f61c.png"
		elsif bac < 0.13
			return "https://abs.twimg.com/emoji/v1/72x72/1f61d.png"
		else
			return "https://abs.twimg.com/emoji/v1/72x72/1f632.png"
		end
	end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/_bars.html.erb
<% if User.find(session[:user_id]).booze_level < 2 %>

<% @barlist.each do |bar| %>
	<div class="place-item">
		<div class="icon-logo restaurant">
			<% if bar[:type] == "wine" %>
				<img src="https://abs.twimg.com/emoji/v1/72x72/1f377.png">
			<% else %>
				<img src="https://abs.twimg.com/emoji/v1/72x72/1f378.png">
			<% end %>
		</div>
		<div class="info">
			<h3><%= bar[:name] %></h3>
			<p><%= bar[:address] %> </p>
			<p>Rating: <%= bar[:rating] %> </p>
			<% @uberurl = @uberurl_1 + @uberurl_2 + bar[:lat].to_s + @uberurl_3 + bar[:long].to_s %>
			<%= link_to "Uber", @uberurl, :class => "uber-button", :target => "_blank " %>
		</div>
		<br />
	</div><br>
<% end %>

<% else %>

<% @barlist.each do |bar| %>
	<div class="place-item">
		<div class="icon-logo restaurant">
			<% if bar[:type] == "wine" %>
				<img src="https://abs.twimg.com/emoji/v1/72x72/1f377.png">
			<% else %>
				<img src="https://abs.twimg.com/emoji/v1/72x72/1f378.png">
			<% end %>
		</div>
		<div class="info big">
			<h3 class="big"><%= bar[:name] %></h3>
			<% @uberurl = @uberurl_1 + @uberurl_2 + bar[:lat].to_s + @uberurl_3 + bar[:long].to_s %>
			<%= link_to "Uber", @uberurl, :class => "uber-button big" %>
		</div>
		<br />
	</div><br><br>
<% end %>

<% end %>

app/views/main/admin.html.erb
<%= form_tag set_bac_url, method: "post" do %>
  <%= number_field_tag 'bac', 0.0, in: 0.00..0.40, :step => 0.01 %>
  <%= submit_tag "SET" %>
<% end %>

app/views/main/bac.html.erb
<% if @booze_level == 0 %>

<%= link_to get_bac_url do %> 
	<div class="bac-button zero">
		<div class="text">WHAT IS MY BAC?</div>
	</div>
<% end %>

<% elsif @booze_level == 1 %>

<%= link_to get_bac_url do %>  
	<div class="bac-button one">
		<div class="text">HOW DRUNK AM I?</div>
	</div>
<% end %>

<% elsif @booze_level == 2 %>

<%= link_to get_bac_url do %> 
	<div class="bac-button two">
		<div class="text">AM &nbsp;I&nbsp; DRUNK?</div>
	</div>
<% end %>

<% else %>

<%= link_to get_bac_url do %> 
	<div class="bac-button three">
		<div class="text">DRUNK?</div>
	</div>
<% end %>

<% end %>

<% if @booze_level > 1 %>
	<div class="barstools nite">
	</div>
<% else %>
	<div class="barstools">
	</div>
<% end %>

app/views/main/bars.html.erb
<h1>DRINK UP <div class="label-emoji"><img src="https://abs.twimg.com/emoji/v1/72x72/1f379.png"></div></h1>
<%= render "bars"%>

app/views/main/choose.html.erb
<h1>
	<% if @user.booze_level == 0 %>
		SOBER SALLY <div class="label-emoji"><img src="https://abs.twimg.com/emoji/v1/72x72/1f481.png"></div>
	<% elsif @user.booze_level == 1 %>
		TIPSY TURVEY <div class="label-emoji"><img src="https://abs.twimg.com/emoji/v1/72x72/1f4ef.png"></div>
	<% elsif @user.booze_level == 2 %>
		YOU'RE DRUNK! <div class="label-emoji"><img src="https://abs.twimg.com/emoji/v1/72x72/1f389.png"></div>
	<% else %>
		HAMMERED <div class="label-emoji"><img src="https://abs.twimg.com/emoji/v1/72x72/1f528.png"></div>
	<% end %>
</h1>

<% if @user.booze_level < 2 %>
	<h1 id="bac">
<% else %>
	<h1 id="bac" class="nite">
<% end %>
	<%= @user.latest_bac %>
</h1>

<% unless @time.nil? %>
	<p class='timestamp'><%= @time %></p>
<% end %>

<% if @user.booze_level == 0 %>
  <h2>You look like you could use a drink. <div class="option-emoji"><img src="https://abs.twimg.com/emoji/v1/72x72/1f379.png"></div></h2>
  <%= render "bars"%>
<% end %>

<% if @user.booze_level == 1 %>
	<%= link_to bars_url do %>
		<div class="option-button">
			<div class="text">
				KEEP GOING, BRAH
				<div class="button-emoji"><img src="https://abs.twimg.com/emoji/v1/72x72/1f379.png"></div>
			</div>
		</div>
	<% end %>
	<%= link_to food_url do %>
		<div class="option-button">
			<div class="text">
				LATE NITE NOMS
				<div class="button-emoji"><img src="https://abs.twimg.com/emoji/v1/72x72/1f374.png"></div>
			</div>
		</div>
	<% end %>
<% elsif @user.booze_level == 2  %>
<%= link_to bars_url do %>
		<div class="option-button two">
			<div class="text">
				KEEP GOING, BRAH
				<div class="button-emoji"><img src="https://abs.twimg.com/emoji/v1/72x72/1f379.png"></div>
			</div>
		</div>
	<% end %>
	<%= link_to food_url do %>
		<div class="option-button two">
			<div class="text">
				LATE NITE NOMS
				<div class="button-emoji"><img src="https://abs.twimg.com/emoji/v1/72x72/1f374.png"></div>
			</div>
		</div>
	<% end %>
	<%= link_to @uberurl do %>
		<div class="option-button two">
			<div class="text">
				CALL IT A NIGHT 
				<div class="button-emoji"><img src="https://abs.twimg.com/emoji/v1/72x72/1f698.png"></div>
			</div>
		</div>
	<% end %>
<% end %>

<% if @user.booze_level == 3 %>
<h2 style="font-size: 3em; margin-top: .3em; padding-bottom: .5em;">Go home, <%= @user.first %>.<br>You're drunk.</h2>
  <%= link_to @uberurl do %>
		<div class="option-button three">
			<div class="text">
				UBER
				<div class="button-emoji"><img src="https://abs.twimg.com/emoji/v1/72x72/1f698.png"></div>
			</div>
		</div>
	<% end %>
<% end %> 

app/views/main/food.html.erb
<h1>LATE NITE NOMS <div class="label-emoji"><img src="https://abs.twimg.com/emoji/v1/72x72/1f374.png"></div></h1> 

<table align="center">
	<tr>
		<td><div class="icon-logo"><img src="https://abs.twimg.com/emoji/v1/72x72/1f355.png"></div></td>
		<td><div class="icon-logo"><img src="https://abs.twimg.com/emoji/v1/72x72/1f354.png"></div></td>
		<td><div class="icon-logo"><img src="https://abs.twimg.com/emoji/v1/72x72/1f357.png"></div></td>
	</tr>
	<tr>
		<td><div class="icon-logo"><img src="https://abs.twimg.com/emoji/v1/72x72/1f35d.png"></div></td>
		<td><div class="icon-logo"><img src="https://abs.twimg.com/emoji/v1/72x72/1f35c.png"></div></td>
		<td><div class="icon-logo"><img src="https://abs.twimg.com/emoji/v1/72x72/1f36a.png"></div></td>
	</tr>
</table>

<div class="join-hop">
	<input style="width: 80%; margin: 0 10%;" type="text" class="latlong" placeholder="Search food...">
	<div class="option-button">
		<div class="text">
			SEARCH
		</div>
	</div>
</div>

app/views/main/twilio.html.erb
<h3>Twilio is now set up to text you when it's time to hop bars</h3>

app/views/main/uber.html.erb
<h1>TIME TO GO <div class="label-emoji"><img src="https://abs.twimg.com/emoji/v1/72x72/1f698.png"></div></h1>
	<a href="<%= @uberurl%>">Call an Uber</a>
</div>