config/routes.rb
Hopscotch::Application.routes.draw do
  
  resources :locations
  resources :registrations
  resources :users

  root to: 'main#bac', as: 'bac'

  get "login" => "auth#login", :as => :login
  get "logout" => "auth#logout", :as => :logout
  post "do_login" => "auth#do_login", :as => :do_login
  

  get "bac" => "main#get_bac", :as => :get_bac
  post "bac" => "main#set_bac", :as => :set_bac
  get "admin" => "main#admin", :as => :admin

  get "options" => "main#choose", :as => :choose
  get "options/bars" => "main#bars", :as => :bars
  get "options/food" => "main#food", :as => :food
  get "options/uber" => "main#uber", :as => :uber
  get "options/twilio" => "main#twilio", :as => :twilio

  get "hops" => "hops#index", :as => :hops
  get "hops/new" => "hops#new", :as => :new_hop 
  get "hops/current" => "hops#current", :as => :current_hop
  get "hops/leave" => "hops#leave", :as => :leave_hop
  get "hops/end" => "hops#end_hop", :as => :end_hop
  get "hops/uber_end" => "hops#uber_end", :as => :uber_end
  post "hops/create" => "hops#create", :as => :create_hop
  get "hops/locations" => "hops#pick_locations", :as => :pick_locations
  post "hops/set" => "hops#set_locations", :as => :set_locations
  get "hops/planned" => "hops#plan_created", :as => :plan_created
  get "hops/destination" => "hops#destination", :as => :destination
  post "hops/save_destination" => "hops#save_destination", :as => :save_destination

end

app/models/hop.rb
class Hop < ActiveRecord::Base
	has_many :registrations
  has_many :users, through: :registrations
end

app/controllers/hops_controller.rb
class HopsController < ApplicationController

	before_filter :get_logged_in_user

	def index
		@hops = Hop.all
	end

	def new
	end

	def create
		@hop = Hop.new
		handle = params[:handle]

		if handle == "wing"
			@hop.planned = false
			@hop.code = (0...4).map { ('a'..'z').to_a[rand(26)] }.join
			@hop.save

			@registration = Registration.new
			@registration.user_id = session[:user_id]
			@registration.hop_id = @hop.id
			@registration.active = true
			@registration.save
			#session[:reg_id] = @registration.id

			@user = User.find(session[:user_id])
			@user.current_hop = @registration.id
			
			if @user.save 
				redirect_to destination_url
			else
				render action "new"
			end
		elsif handle == "plan"
			@hop.planned = true
			@hop.code = (0...4).map { ('a'..'z').to_a[rand(26)] }.join
			@hop.save

			@registration = Registration.new
			@registration.user_id = session[:user_id]
			@registration.hop_id = @hop.id
			@registration.active = true
			@registration.save
			#session[:reg_id] = @registration.id

			@user = User.find(session[:user_id])
			@user.current_hop = @registration.id
			
			if @user.save 
				redirect_to destination_url
			else
				render action "new"
			end
		end
	end

	def pick_locations
		# TODO: get actual lat and long from user
		lat = "42.360986"
		long = "-71.096849"
		max_width = "100" #measured in px
		bars_request_string = "https://maps.googleapis.com/maps/api/place/nearbysearch/json?key=AIzaSyBaaEBm7WetJlxmSCcShqvWSqttq63LTB8&location="+lat+","+long+"&rankby=distance&types=bar|night_club"
		bars_uri = URI.parse(URI.encode(bars_request_string))
		bars_https = Net::HTTP.new(bars_uri.host, bars_uri.port)
		bars_https.use_ssl = true
		bars_https.verify_mode = OpenSSL::SSL::VERIFY_NONE # this is NOT secure but Google's API is a free service and we aren't sharing real user data
		bars_request = Net::HTTP::Get.new(bars_uri.request_uri)
		bars_response = bars_https.request(bars_request).body
		results = JSON.parse(bars_response)["results"]
		@barlist = Array.new
		results.each do |r|
			barname = r["name"]
			baraddress = r["vicinity"]
			barlat = r["geometry"]["location"]["lat"]
			barlong = r["geometry"]["location"]["lng"]
			barrating = r["rating"]
			baricon = r["icon"]
			if baricon.include? "wine"
				bartype = "wine"
			else
				bartype = "bar"
			end
			@barlist << {:name => barname, :address => baraddress, :lat => barlat, :long => barlong, :rating => barrating, :type => bartype}
		end
	end

	def set_locations
		@places = params[:locations]
	end

	def plan_created
		@params = params
		@count = params["count"].to_i

		for i in 0..@count
		  @loc = Location.new
			@loc.name = params[i.to_s + "-name"].to_s
			@loc.time = params[i.to_s].to_s
			@loc.registration_id = User.find(session[:user_id]).current_hop
			@loc.save
			##SLEEPSCOTCH HERE
			plan_uri = URI.parse("http://sleepscotch-hackmit.herokuapp.com/receive/10:01am/Harpers/+3174167556")
			Net::HTTP.new(plan_uri.host, plan_uri.port)
		end

		redirect_to current_hop_url
	end

	def destination
		@user = User.find(session[:user_id])
		if @user.current_hop.nil?
			redirect_to new_hop_url
		end
		@reg_id = @user.current_hop
	end

	def save_destination
		latitude = params[:latitude]
		longitude = params[:latitude]
		@user = User.find(session[:user_id])

		reg = Registration.find(@user.current_hop)
		reg.final_destination_lat = latitude
		reg.final_destination_long = longitude
		if reg.save
			if reg.hop.planned == false
				redirect_to bac_url
			elsif reg.hop.planned == true
				redirect_to pick_locations_url
			end
		end
	end

	def current
		@user = User.find(session[:user_id])
		if @user.current_hop.nil?
			redirect_to new_hop_url
		end
		@reg = Registration.find(@user.current_hop)
	end

	def leave
		if User.find(session[:user_id]).current_hop.nil?
			redirect_to new_hop_url
		end
		@check = User.find(session[:user_id]).current_hop
	end

	def uber_end 
		@user = User.find(session[:user_id])
		if @user.current_hop.nil?
			redirect_to new_hop_url
		end
		@reg = Registration.find(35)
		firstname = @user.first
		lastname = @user.last
		phone = @user.phone

		uberdestination = "229%20Commonwealth%20Ave%2C%20Boston%2C%20MA%2002116"
		@uberurl = "https://m.uber.com/sign-up?client_id=a-RTv0w8VfNjNR0oTUio1LXBDrjrBIUx"
		@uberurl += "&first_name="+firstname+"&last_name="+lastname+"&mobile_phone="+phone #+"&dropoff_address="+uberdestination
		@uberurl += "&dropoff_latitude=" + @reg.final_destination_lat
		@uberurl += "&dropoff_longitude=" + @reg.final_destination_long

		user = User.find(session[:user_id])
		reg = Registration.find(user.current_hop)
		reg.active = false
		reg.save
		user.current_hop = nil
		user.save
		redirect_to(@uberurl)
	end

	def end_hop
		user = User.find(session[:user_id])
		unless user.current_hop.nil?
			reg = Registration.find(user.current_hop)
			reg.active = false
			reg.save
			user.current_hop = nil
			user.save
		end
		redirect_to new_hop_url
	end

	def destroy
    @hop = Hop.find params[:id]
    user = User.find(session[:user_id])

    if user.current_hop == @hop.id
    	user.current_hop = nil
    	user.save
    end


    @hop.destroy
    redirect_to hops_url
  end
end

app/helpers/hops_helper.rb
module HopsHelper
end

app/views/hops/create.html.erb
<%if @user.save %>
success
<% else %>
fail
<% end %>

app/views/hops/current.html.erb
<h1>HOPSCOTCH</h1>

<ul>
<% @reg.locations.each do |loc| %>
	<li><%= loc.name %> <b><%= loc.time %></b></li>
<% end %>
</ul>

app/views/hops/destination.html.erb
<h1>WHERE SHOULD YOU END UP?</h1>
<p>Please enter the latitude and longitude of your final desination tonight. This is where your Uber driver will deliver you at the end of the night.</p>

<%= form_tag save_destination_url, method: "post" do %>
	<%= text_field_tag 'latitude', nil, :placeholder => 'Latitude', :class => "latlong" %>
	<%= text_field_tag 'longitude', nil, :placeholder => 'Longitude', :class => "latlong" %>
	<div class="option-button">
		<div class="text">
			<%= submit_tag "THAT'S THE PLACE", :class => "submit" %> 
			<div class="button-emoji"><img src="https://abs.twimg.com/emoji/v1/72x72/1f698.png"></div>
		</div>
	</div>
<% end %>

app/views/hops/index.html.erb
<h1>hops</hi>

<h2> List of hops </h2>
<ul>
<% @hops.each do |hop| %>
<li>
<%= hop.code %> ( <%= link_to "Delete", hop_url(hop), method: 'delete' %>)
</li>
<% end %>
</ul>

app/views/hops/leave.html.erb
<h1>CALLIN' IT A NIGHT <div class="label-emoji"><img src="https://abs.twimg.com/emoji/v1/72x72/1f634.png"></div></h1>

<%= link_to uber_end_url do %>
<div class="option-button">
	<div class="text">
		ORDER AN UBER
	</div>
</div>
<% end %>

<%= link_to end_hop_url do %>
<div class="option-button blue">
	<div class="text">
		JUST QUIT
	</div>
</div>
<% end %>

app/views/hops/new.html.erb
<h1>BEGIN &nbsp;A&nbsp; HOP</h1>

<%= form_tag create_hop_url, method: "post" do %>
	<div class="option-button">
		<div class="text">
			<%= submit_tag "MAKE A GAME PLAN", :class => "submit" %> 
			<div class="button-emoji"><img src="https://abs.twimg.com/emoji/v1/72x72/1f3af.png"></div>
		</div>
	</div>
	<%= hidden_field_tag "handle", "plan" %>
<% end %>

<%= form_tag create_hop_url, method: "post" do %>
	<div class="option-button">
		<div class="text">
			<%= submit_tag "WING IT", :class => "submit" %> 
			<div class="button-emoji"><img src="https://abs.twimg.com/emoji/v1/72x72/1f413.png"></div>
		</div>
	</div>
	<%= hidden_field_tag "handle", "wing" %>
<% end %>

<div class="join-hop">
	<%= form_tag create_hop_url, method: "post" do %>
	  <%= text_field_tag 'join-code' %>
		<div class="option-button">
			<div class="text">
				JOIN A HOP
				<div class="button-emoji"><img src="https://abs.twimg.com/emoji/v1/72x72/1f46f.png"></div>
			</div>
		</div>
	<% end %>
</div>

app/views/hops/pick_locations.html.erb
<h1>PLAN YOUR ADVENTURE</h1>

<%= form_tag set_locations_url, method: "post" do %>

	<% @barlist.each do |bar| %>
		<div class="place-item">
			<div class="icon-logo restaurant">
				<% if bar[:type] == "wine" %>
					<img src="https://abs.twimg.com/emoji/v1/72x72/1f377.png">
				<% else %>
					<img src="https://abs.twimg.com/emoji/v1/72x72/1f378.png">
				<% end %>
			</div>
			<div class="info">
				<h3><%= bar[:name] %></h3>
				<p><%= bar[:address] %> </p>
				<p>Rating: <%= bar[:rating] %> </p>
			</div>
			<br />
			<input type="checkbox" name="locations[]" value="<%= bar[:name] %>">
		</div><br>
	<% end %>

	<div class="option-button">
		<div class="text">
			<%= submit_tag "SELECT LOCATIONS", :class => "submit" %>
		</div>
	</div>
<% end %>

app/views/hops/set_locations.html.erb
<h1>SET A SCHEDULE</h1>


<%= form_tag plan_created_url, method: "get" do %>
<div class="set_locations">
  <% @x = 0 %>
	<% @places.each do |place| %>
		<%= label @x, place %>
		<%= text_field_tag @x, nil, placeholder: 'time' %>
		<%= hidden_field_tag @x.to_s + "-name", place %><br>
		<% @x += 1 %>
	<% end %>
</div>

<%= hidden_field_tag 'count', @x - 1 %>
	<div class="option-button">
		<div class="text">
			<%= submit_tag "SEAL THE DEAL", :class => "submit" %>
		</div>
	</div>
<% end %>