config/routes.rb
Hopscotch::Application.routes.draw do
  
  resources :locations
  resources :registrations
  resources :users

  root to: 'main#bac', as: 'bac'

  get "login" => "auth#login", :as => :login
  get "logout" => "auth#logout", :as => :logout
  post "do_login" => "auth#do_login", :as => :do_login
  

  get "bac" => "main#get_bac", :as => :get_bac
  post "bac" => "main#set_bac", :as => :set_bac
  get "admin" => "main#admin", :as => :admin

  get "options" => "main#choose", :as => :choose
  get "options/bars" => "main#bars", :as => :bars
  get "options/food" => "main#food", :as => :food
  get "options/uber" => "main#uber", :as => :uber
  get "options/twilio" => "main#twilio", :as => :twilio

  get "hops" => "hops#index", :as => :hops
  get "hops/new" => "hops#new", :as => :new_hop 
  get "hops/current" => "hops#current", :as => :current_hop
  get "hops/leave" => "hops#leave", :as => :leave_hop
  get "hops/end" => "hops#end_hop", :as => :end_hop
  get "hops/uber_end" => "hops#uber_end", :as => :uber_end
  post "hops/create" => "hops#create", :as => :create_hop
  get "hops/locations" => "hops#pick_locations", :as => :pick_locations
  post "hops/set" => "hops#set_locations", :as => :set_locations
  get "hops/planned" => "hops#plan_created", :as => :plan_created
  get "hops/destination" => "hops#destination", :as => :destination
  post "hops/save_destination" => "hops#save_destination", :as => :save_destination

end

app/models/user.rb
class User < ActiveRecord::Base
	validates :username, :presence => true, :uniqueness => true
  validates :email, :presence => true, :uniqueness => true
  validates :password, :presence => true, :confirmation => true
  validates :first, :presence => true
  validates :last, :presence => true
  validates :phone, :presence => true

  has_many :registrations
  has_many :hops, through: :registrations
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

	def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:username, :email, :password, :password_confirmation, :first, :last, :phone, :bactrack_id)
    @user = User.new user_params
    if (@user.save)
      session[:user_id] = @user.id
      redirect_to bac_url
    else
      render action: 'new'
    end
  end

  def destroy
    @user = User.find params[:id]
    @user.destroy
    redirect_to users_url
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h1>users</hi>

<h2> List of People </h2>
<ul>
<% @users.each do |user| %>
<li>
<%= user.first %> (<%= link_to "View", user %>, <%= link_to "Edit", edit_user_url(user) %>, 
  <%= link_to "Delete", user_url(user), method: 'delete' %>)
</li>
<% end %>
</ul>
<%= link_to "Add a New user", new_user_url %>

	

app/views/users/new.html.erb
<h2> New user </h2>

<%= form_for @user do |f| %>
 <% if @user.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <%= f.label :username, "Username:" %> <%= f.text_field :username %><br />
  <%= f.label :email, "Email:" %> <%= f.text_field :email %><br />
  <%= f.label :password, "Password:" %> <%= f.password_field :password %><br />
  Confirm: <%= f.password_field :password_confirmation %>  <br />
  <%= f.label :first, "First name:" %> <%= f.text_field :first %><br />
  <%= f.label :last, "Last name:" %> <%= f.text_field :last %><br />
  <%= f.label :phone, "Phone:" %> <%= f.text_field :phone %><br />
  <%= f.label :bactrack_id, "BACtrack ID:" %> <%= f.text_field :bactrack_id %><br />
  <%= f.submit %>
<% end %>
<hr />
<%= link_to "Cancel", bac_url %>