config/routes.rb
Hopscotch::Application.routes.draw do
  
  resources :locations
  resources :registrations
  resources :users

  root to: 'main#bac', as: 'bac'

  get "login" => "auth#login", :as => :login
  get "logout" => "auth#logout", :as => :logout
  post "do_login" => "auth#do_login", :as => :do_login
  

  get "bac" => "main#get_bac", :as => :get_bac
  post "bac" => "main#set_bac", :as => :set_bac
  get "admin" => "main#admin", :as => :admin

  get "options" => "main#choose", :as => :choose
  get "options/bars" => "main#bars", :as => :bars
  get "options/food" => "main#food", :as => :food
  get "options/uber" => "main#uber", :as => :uber
  get "options/twilio" => "main#twilio", :as => :twilio

  get "hops" => "hops#index", :as => :hops
  get "hops/new" => "hops#new", :as => :new_hop 
  get "hops/current" => "hops#current", :as => :current_hop
  get "hops/leave" => "hops#leave", :as => :leave_hop
  get "hops/end" => "hops#end_hop", :as => :end_hop
  get "hops/uber_end" => "hops#uber_end", :as => :uber_end
  post "hops/create" => "hops#create", :as => :create_hop
  get "hops/locations" => "hops#pick_locations", :as => :pick_locations
  post "hops/set" => "hops#set_locations", :as => :set_locations
  get "hops/planned" => "hops#plan_created", :as => :plan_created
  get "hops/destination" => "hops#destination", :as => :destination
  post "hops/save_destination" => "hops#save_destination", :as => :save_destination

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hopscotch</title>
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700|Grand+Hotel' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= favicon_link_tag 'favicon.png' %>
  <%= csrf_meta_tags %>
</head>
<% @user = session[:user_id].nil? ? nil :  User.find(session[:user_id]) %>
<% if @user.nil? || @user.booze_level < 2 %>
	<body>
<% else %>
	<body class="nite">
<% end %>
	<% if @user.nil? || @user.booze_level < 2 %>
		<div id="core">
	<% else %>
		<div id="core" class="nite">
	<% end %>
		<% if @user.nil? || @user.booze_level < 2 %>
			<header>
		<% else %>
			<header class="nite">
		<% end %>
			<% unless @user.nil? %>
			<nav>
				<div class="menu-icon">
					<% if @user.nil? || @user.booze_level < 2 %>
						<%= image_tag "menu-icon.png" %>
					<% else %>
						<%= image_tag "menu-icon_nite.png" %>
					<% end %>
				</div>
			</nav>
			<% end %>
			<div id="logo">
				<%= link_to bac_url do %>      
					<% if @user.nil? || @user.booze_level < 2 %>
						<%= image_tag "hopscotch.png" %>
					<% else %>
						<%= image_tag "hopscotch_nite.png" %>
					<% end %>
				<% end %>
			</div>
			<% unless @user.nil? %>
			<div id="drunk-o-meter">
				<!--div class="text"-->
					<!-- DRUNK 'O' METER -->
				<!--/div-->
				<div id="drunk-emoji">
					<img src="<%= @user.drunk_emoji %>">
				</div>
			</div>
			<% if @user.nil? || @user.booze_level < 2 %>
				<ul>
			<% else %>
				<ul class="nite">
			<% end %>
				<% if @user.current_hop.nil? %>
					<li><%= link_to "Begin a Hop", new_hop_url %></li>
				<% elsif Registration.find(@user.current_hop).hop.planned == false %>
				  <li><%= link_to "End Hop", leave_hop_url %></li>
				<% else %>
				  <li><%= link_to "Current Hop", current_hop_url %></li>
				  <li><%= link_to "Leave Hop", leave_hop_url %></li>
				<% end %>
	 			<li><%= link_to "Logout", logout_url %></li>
	 		</ul>
	 		<% end %>
		</header>

		<%= yield %>
		<div class="push"></div>
	</div>
	<footer>
	</footer>
	<%= javascript_include_tag "nav"%>
</body>
</html>